//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSystems.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FixedDeposit
    {
        [Key, Column(Order = 0)]
        public int SerialNumber { get; set; }
        public string AccountName { get; set; }

        [Key, Column(Order = 1)]
        public string BankName { get; set; }
        public string FDNumber { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RateOfInterest { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<decimal> MaturityAmount { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
