//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchSystems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryDistribution
    {
        public int Id { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> PFAmount { get; set; }
        public Nullable<int> GratuityAmount { get; set; }
        public Nullable<int> InsuranceAmount { get; set; }
        public Nullable<int> MessCharges { get; set; }
        public Nullable<int> AccomodationCharges { get; set; }
        public Nullable<int> GrandSalary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
